// <auto-generated />
using System;
using BarelyGambling.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BarelyGambling.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210428101257_init3")]
    partial class init3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BarelyGambling.Core.Entity.Bidding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("Bidding");
                });

            modelBuilder.Entity("BarelyGambling.Core.Entity.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("BiddingRestrictedTos")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Total")
                        .HasColumnType("real");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Won")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Team");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5db63212-9e2f-4200-8e58-93b05c25e8c7"),
                            BiddingRestrictedTos = 0f,
                            Description = "Sample description for A1 Grand Prix Team 1",
                            Title = "A1 Grand Prix Team 1",
                            Total = 0f,
                            TournamentId = new Guid("d2bea1cd-0754-4cb8-831a-fb621f8fc34c"),
                            Won = true
                        },
                        new
                        {
                            Id = new Guid("0fd4f642-20a5-4076-8e30-cdecf6fee415"),
                            BiddingRestrictedTos = 0f,
                            Description = "Sample description for A1 Grand Prix Team 2",
                            Title = "A1 Grand Prix Team 2",
                            Total = 0f,
                            TournamentId = new Guid("d2bea1cd-0754-4cb8-831a-fb621f8fc34c"),
                            Won = false
                        },
                        new
                        {
                            Id = new Guid("c08374e7-a236-482d-878a-6db6c7b4e573"),
                            BiddingRestrictedTos = 0f,
                            Description = "Sample description for Formula One World Championship Team 1",
                            Title = "Formula One World Championship Team 1",
                            Total = 0f,
                            TournamentId = new Guid("416e23f6-0aa1-4e15-af12-2afde162d6a5"),
                            Won = true
                        },
                        new
                        {
                            Id = new Guid("73c7be01-268a-4d31-921e-d3fa860a0768"),
                            BiddingRestrictedTos = 0f,
                            Description = "Sample description for Formula One World Championship Team 2",
                            Title = "Formula One World Championship Team 2",
                            Total = 0f,
                            TournamentId = new Guid("416e23f6-0aa1-4e15-af12-2afde162d6a5"),
                            Won = false
                        },
                        new
                        {
                            Id = new Guid("ee7ba12c-ef9d-405e-b45d-3acb8fb3394d"),
                            BiddingRestrictedTos = 0f,
                            Description = "Sample description for FIA World Endurance Championship Team 1",
                            Title = "FIA World Endurance Championship Team 1",
                            Total = 0f,
                            TournamentId = new Guid("cbfb02a9-7ea4-4c27-bd99-f726127e6af3"),
                            Won = true
                        },
                        new
                        {
                            Id = new Guid("b2a8bff2-dfd9-4ca2-bde3-bf217b592554"),
                            BiddingRestrictedTos = 0f,
                            Description = "Sample description for FIA World Endurance Championship Team 2",
                            Title = "FIA World Endurance Championship Team 2",
                            Total = 0f,
                            TournamentId = new Guid("cbfb02a9-7ea4-4c27-bd99-f726127e6af3"),
                            Won = false
                        },
                        new
                        {
                            Id = new Guid("eb2bee40-6b9d-4422-b7c7-f1a4a54c01ff"),
                            BiddingRestrictedTos = 0f,
                            Description = "Sample description for FIA GT1 World Championship Team 1",
                            Title = "FIA GT1 World Championship Team 1",
                            Total = 0f,
                            TournamentId = new Guid("32a8201b-939c-46c2-bd90-38660021836a"),
                            Won = true
                        },
                        new
                        {
                            Id = new Guid("b4715dd4-cb27-43b8-bd8b-172da55c983a"),
                            BiddingRestrictedTos = 0f,
                            Description = "Sample description for FIA GT1 World Championship Team 2",
                            Title = "FIA GT1 World Championship Team 2",
                            Total = 0f,
                            TournamentId = new Guid("32a8201b-939c-46c2-bd90-38660021836a"),
                            Won = false
                        },
                        new
                        {
                            Id = new Guid("ec477169-6883-49c0-9d0e-0ed966fd7e14"),
                            BiddingRestrictedTos = 0f,
                            Description = "Sample description for World Gliding Championships Team 1",
                            Title = "World Gliding Championships Team 1",
                            Total = 0f,
                            TournamentId = new Guid("b1c5b2e6-ad5f-416f-b66c-eeb0b1444b79"),
                            Won = true
                        },
                        new
                        {
                            Id = new Guid("1a9ddbe8-ba40-4735-9022-25333119f96e"),
                            BiddingRestrictedTos = 0f,
                            Description = "Sample description for World Gliding Championships Team 2",
                            Title = "World Gliding Championships Team 2",
                            Total = 0f,
                            TournamentId = new Guid("b1c5b2e6-ad5f-416f-b66c-eeb0b1444b79"),
                            Won = false
                        });
                });

            modelBuilder.Entity("BarelyGambling.Core.Entity.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("TeamMember");

                    b.HasData(
                        new
                        {
                            Id = new Guid("73443d29-1337-4119-9139-6ebb54b2ca64"),
                            TeamId = new Guid("5db63212-9e2f-4200-8e58-93b05c25e8c7"),
                            UserId = new Guid("6c78ad50-8a96-4a1b-a9ee-2fbeb63aa6ed")
                        },
                        new
                        {
                            Id = new Guid("e0989077-21ad-415c-ae2a-ea1723a93b72"),
                            TeamId = new Guid("5db63212-9e2f-4200-8e58-93b05c25e8c7"),
                            UserId = new Guid("6c78ad50-8a96-4a1b-a9ee-2fbeb63aa6ed")
                        },
                        new
                        {
                            Id = new Guid("f852819b-2411-44be-8ebc-b8302cb0bf16"),
                            TeamId = new Guid("0fd4f642-20a5-4076-8e30-cdecf6fee415"),
                            UserId = new Guid("6c78ad50-8a96-4a1b-a9ee-2fbeb63aa6ed")
                        },
                        new
                        {
                            Id = new Guid("0400f394-be0a-4603-a543-ab9d422cc17b"),
                            TeamId = new Guid("0fd4f642-20a5-4076-8e30-cdecf6fee415"),
                            UserId = new Guid("6c78ad50-8a96-4a1b-a9ee-2fbeb63aa6ed")
                        },
                        new
                        {
                            Id = new Guid("b90e5ff3-644c-47b8-b9fd-307f1b20557b"),
                            TeamId = new Guid("c08374e7-a236-482d-878a-6db6c7b4e573"),
                            UserId = new Guid("d0ead67c-717f-4df1-816c-844652df604f")
                        },
                        new
                        {
                            Id = new Guid("f7adc539-d33c-4e08-823c-c460bbc2d255"),
                            TeamId = new Guid("c08374e7-a236-482d-878a-6db6c7b4e573"),
                            UserId = new Guid("d0ead67c-717f-4df1-816c-844652df604f")
                        },
                        new
                        {
                            Id = new Guid("6d237c92-a109-439c-aa1f-a552656adcd5"),
                            TeamId = new Guid("73c7be01-268a-4d31-921e-d3fa860a0768"),
                            UserId = new Guid("d0ead67c-717f-4df1-816c-844652df604f")
                        },
                        new
                        {
                            Id = new Guid("3b8b92a2-65e6-48bb-96c5-f2412bd90d45"),
                            TeamId = new Guid("73c7be01-268a-4d31-921e-d3fa860a0768"),
                            UserId = new Guid("d0ead67c-717f-4df1-816c-844652df604f")
                        },
                        new
                        {
                            Id = new Guid("981b1857-0158-4f67-aa29-d561e4007191"),
                            TeamId = new Guid("ee7ba12c-ef9d-405e-b45d-3acb8fb3394d"),
                            UserId = new Guid("a6bcdd93-d29e-402a-b866-c765817a2461")
                        },
                        new
                        {
                            Id = new Guid("a41ecf7d-5eb9-4b4b-944c-a6abc107261d"),
                            TeamId = new Guid("ee7ba12c-ef9d-405e-b45d-3acb8fb3394d"),
                            UserId = new Guid("a6bcdd93-d29e-402a-b866-c765817a2461")
                        },
                        new
                        {
                            Id = new Guid("89933ebb-8f12-45a8-9601-8c472e4ed913"),
                            TeamId = new Guid("b2a8bff2-dfd9-4ca2-bde3-bf217b592554"),
                            UserId = new Guid("a6bcdd93-d29e-402a-b866-c765817a2461")
                        },
                        new
                        {
                            Id = new Guid("e698c7c0-6796-4ebb-9e0d-fcbcd7b0242b"),
                            TeamId = new Guid("b2a8bff2-dfd9-4ca2-bde3-bf217b592554"),
                            UserId = new Guid("a6bcdd93-d29e-402a-b866-c765817a2461")
                        },
                        new
                        {
                            Id = new Guid("091a2d02-fd04-4a38-a7b3-13da3cda8802"),
                            TeamId = new Guid("eb2bee40-6b9d-4422-b7c7-f1a4a54c01ff"),
                            UserId = new Guid("24485364-9105-4ccd-b5c2-171b691f185d")
                        },
                        new
                        {
                            Id = new Guid("4d57e93f-ce8b-41da-a685-7b03661f4535"),
                            TeamId = new Guid("eb2bee40-6b9d-4422-b7c7-f1a4a54c01ff"),
                            UserId = new Guid("24485364-9105-4ccd-b5c2-171b691f185d")
                        },
                        new
                        {
                            Id = new Guid("27852c66-bac6-49a4-964c-6b8635993e59"),
                            TeamId = new Guid("b4715dd4-cb27-43b8-bd8b-172da55c983a"),
                            UserId = new Guid("24485364-9105-4ccd-b5c2-171b691f185d")
                        },
                        new
                        {
                            Id = new Guid("8ef2c523-5d0d-481a-9b09-9c02c53453fd"),
                            TeamId = new Guid("b4715dd4-cb27-43b8-bd8b-172da55c983a"),
                            UserId = new Guid("24485364-9105-4ccd-b5c2-171b691f185d")
                        },
                        new
                        {
                            Id = new Guid("ad868821-302f-4f31-89e3-b4e82c338572"),
                            TeamId = new Guid("ec477169-6883-49c0-9d0e-0ed966fd7e14"),
                            UserId = new Guid("594a8031-bbbe-4a93-b63b-848d83c57144")
                        },
                        new
                        {
                            Id = new Guid("76c1f6bd-9280-4111-ad5c-151d5140a824"),
                            TeamId = new Guid("ec477169-6883-49c0-9d0e-0ed966fd7e14"),
                            UserId = new Guid("594a8031-bbbe-4a93-b63b-848d83c57144")
                        },
                        new
                        {
                            Id = new Guid("612fc868-6ac0-4c38-8ec1-9245f804e0d3"),
                            TeamId = new Guid("1a9ddbe8-ba40-4735-9022-25333119f96e"),
                            UserId = new Guid("594a8031-bbbe-4a93-b63b-848d83c57144")
                        },
                        new
                        {
                            Id = new Guid("f438c7db-1556-4535-8382-7f83d229bcd8"),
                            TeamId = new Guid("1a9ddbe8-ba40-4735-9022-25333119f96e"),
                            UserId = new Guid("594a8031-bbbe-4a93-b63b-848d83c57144")
                        });
                });

            modelBuilder.Entity("BarelyGambling.Core.Entity.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TournamentPrize")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Tournament");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2bea1cd-0754-4cb8-831a-fb621f8fc34c"),
                            CreatedAt = new DateTime(2021, 4, 28, 15, 42, 57, 36, DateTimeKind.Local).AddTicks(820),
                            CreatedBy = new Guid("6c78ad50-8a96-4a1b-a9ee-2fbeb63aa6ed"),
                            Description = "Sample description for A1 Grand Prix",
                            Place = "Los Angeles",
                            StartingDate = new DateTime(2021, 5, 3, 15, 42, 57, 34, DateTimeKind.Local).AddTicks(7186),
                            Title = "A1 Grand Prix",
                            TournamentPrize = 29628888f
                        },
                        new
                        {
                            Id = new Guid("416e23f6-0aa1-4e15-af12-2afde162d6a5"),
                            CreatedAt = new DateTime(2021, 4, 28, 15, 42, 57, 37, DateTimeKind.Local).AddTicks(5846),
                            CreatedBy = new Guid("d0ead67c-717f-4df1-816c-844652df604f"),
                            Description = "Sample description for Formula One World Championship",
                            Place = "Los Angeles",
                            StartingDate = new DateTime(2021, 4, 28, 15, 42, 57, 37, DateTimeKind.Local).AddTicks(5804),
                            Title = "Formula One World Championship",
                            TournamentPrize = 52812552f
                        },
                        new
                        {
                            Id = new Guid("cbfb02a9-7ea4-4c27-bd99-f726127e6af3"),
                            CreatedAt = new DateTime(2021, 4, 28, 15, 42, 57, 37, DateTimeKind.Local).AddTicks(6565),
                            CreatedBy = new Guid("a6bcdd93-d29e-402a-b866-c765817a2461"),
                            Description = "Sample description for FIA World Endurance Championship",
                            Place = "Los Angeles",
                            StartingDate = new DateTime(2021, 5, 6, 15, 42, 57, 37, DateTimeKind.Local).AddTicks(6559),
                            Title = "FIA World Endurance Championship",
                            TournamentPrize = 5298869f
                        },
                        new
                        {
                            Id = new Guid("32a8201b-939c-46c2-bd90-38660021836a"),
                            CreatedAt = new DateTime(2021, 4, 28, 15, 42, 57, 37, DateTimeKind.Local).AddTicks(6908),
                            CreatedBy = new Guid("24485364-9105-4ccd-b5c2-171b691f185d"),
                            Description = "Sample description for FIA GT1 World Championship",
                            Place = "Los Angeles",
                            StartingDate = new DateTime(2021, 5, 2, 15, 42, 57, 37, DateTimeKind.Local).AddTicks(6903),
                            Title = "FIA GT1 World Championship",
                            TournamentPrize = 46675196f
                        },
                        new
                        {
                            Id = new Guid("b1c5b2e6-ad5f-416f-b66c-eeb0b1444b79"),
                            CreatedAt = new DateTime(2021, 4, 28, 15, 42, 57, 37, DateTimeKind.Local).AddTicks(7247),
                            CreatedBy = new Guid("594a8031-bbbe-4a93-b63b-848d83c57144"),
                            Description = "Sample description for World Gliding Championships",
                            Place = "Los Angeles",
                            StartingDate = new DateTime(2021, 5, 7, 15, 42, 57, 37, DateTimeKind.Local).AddTicks(7242),
                            Title = "World Gliding Championships",
                            TournamentPrize = 10156761f
                        });
                });

            modelBuilder.Entity("BarelyGambling.Core.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0c8f33ce-8adf-4600-986c-8f4900c64f1b"),
                            CoverUrl = "https://via.placeholder.com/150",
                            Email = "MichaelJames1@gmail.com",
                            FirstName = "Michael",
                            LastName = "James",
                            Password = "$2a$11$Hx.1.HZkvkfw7T52BbdhLuJQAhdvR5Y.1nSvwCxJ1sK9paLLtqi5S",
                            UserName = "MichaelJames1"
                        },
                        new
                        {
                            Id = new Guid("6c78ad50-8a96-4a1b-a9ee-2fbeb63aa6ed"),
                            CoverUrl = "https://via.placeholder.com/150",
                            Email = "MichaelWilliam2@gmail.com",
                            FirstName = "Michael",
                            LastName = "William",
                            Password = "$2a$11$Hx.1.HZkvkfw7T52BbdhLuJQAhdvR5Y.1nSvwCxJ1sK9paLLtqi5S",
                            UserName = "MichaelWilliam2"
                        },
                        new
                        {
                            Id = new Guid("d0ead67c-717f-4df1-816c-844652df604f"),
                            CoverUrl = "https://via.placeholder.com/150",
                            Email = "JohnThomas3@gmail.com",
                            FirstName = "John",
                            LastName = "Thomas",
                            Password = "$2a$11$Hx.1.HZkvkfw7T52BbdhLuJQAhdvR5Y.1nSvwCxJ1sK9paLLtqi5S",
                            UserName = "JohnThomas3"
                        },
                        new
                        {
                            Id = new Guid("a6bcdd93-d29e-402a-b866-c765817a2461"),
                            CoverUrl = "https://via.placeholder.com/150",
                            Email = "JosephJohn4@gmail.com",
                            FirstName = "Joseph",
                            LastName = "John",
                            Password = "$2a$11$Hx.1.HZkvkfw7T52BbdhLuJQAhdvR5Y.1nSvwCxJ1sK9paLLtqi5S",
                            UserName = "JosephJohn4"
                        },
                        new
                        {
                            Id = new Guid("24485364-9105-4ccd-b5c2-171b691f185d"),
                            CoverUrl = "https://via.placeholder.com/150",
                            Email = "JohnDavid5@gmail.com",
                            FirstName = "John",
                            LastName = "David",
                            Password = "$2a$11$Hx.1.HZkvkfw7T52BbdhLuJQAhdvR5Y.1nSvwCxJ1sK9paLLtqi5S",
                            UserName = "JohnDavid5"
                        },
                        new
                        {
                            Id = new Guid("594a8031-bbbe-4a93-b63b-848d83c57144"),
                            CoverUrl = "https://via.placeholder.com/150",
                            Email = "MichaelMichael6@gmail.com",
                            FirstName = "Michael",
                            LastName = "Michael",
                            Password = "$2a$11$Hx.1.HZkvkfw7T52BbdhLuJQAhdvR5Y.1nSvwCxJ1sK9paLLtqi5S",
                            UserName = "MichaelMichael6"
                        },
                        new
                        {
                            Id = new Guid("8b92c1d2-222c-4409-931a-fe8c2d662095"),
                            CoverUrl = "https://via.placeholder.com/150",
                            Email = "JamesWilliam7@gmail.com",
                            FirstName = "James",
                            LastName = "William",
                            Password = "$2a$11$Hx.1.HZkvkfw7T52BbdhLuJQAhdvR5Y.1nSvwCxJ1sK9paLLtqi5S",
                            UserName = "JamesWilliam7"
                        },
                        new
                        {
                            Id = new Guid("a89d1159-85cf-48e3-9aad-f770256a1e03"),
                            CoverUrl = "https://via.placeholder.com/150",
                            Email = "JohnJames8@gmail.com",
                            FirstName = "John",
                            LastName = "James",
                            Password = "$2a$11$Hx.1.HZkvkfw7T52BbdhLuJQAhdvR5Y.1nSvwCxJ1sK9paLLtqi5S",
                            UserName = "JohnJames8"
                        },
                        new
                        {
                            Id = new Guid("9899c8bf-24d4-49cd-a533-3cd93b4b64e1"),
                            CoverUrl = "https://via.placeholder.com/150",
                            Email = "JosephRobert9@gmail.com",
                            FirstName = "Joseph",
                            LastName = "Robert",
                            Password = "$2a$11$Hx.1.HZkvkfw7T52BbdhLuJQAhdvR5Y.1nSvwCxJ1sK9paLLtqi5S",
                            UserName = "JosephRobert9"
                        },
                        new
                        {
                            Id = new Guid("5ae9487a-6ea4-4e59-852c-48f60f309b70"),
                            CoverUrl = "https://via.placeholder.com/150",
                            Email = "JosephThomas10@gmail.com",
                            FirstName = "Joseph",
                            LastName = "Thomas",
                            Password = "$2a$11$Hx.1.HZkvkfw7T52BbdhLuJQAhdvR5Y.1nSvwCxJ1sK9paLLtqi5S",
                            UserName = "JosephThomas10"
                        },
                        new
                        {
                            Id = new Guid("6b9323ce-1a5f-4bcf-8ce6-81a992421e03"),
                            CoverUrl = "https://via.placeholder.com/150",
                            Email = "RichardJames11@gmail.com",
                            FirstName = "Richard",
                            LastName = "James",
                            Password = "$2a$11$Hx.1.HZkvkfw7T52BbdhLuJQAhdvR5Y.1nSvwCxJ1sK9paLLtqi5S",
                            UserName = "RichardJames11"
                        },
                        new
                        {
                            Id = new Guid("b8a2508e-fd5f-423a-af6e-1671cf6a2b80"),
                            CoverUrl = "https://via.placeholder.com/150",
                            Email = "RobertWilliam12@gmail.com",
                            FirstName = "Robert",
                            LastName = "William",
                            Password = "$2a$11$Hx.1.HZkvkfw7T52BbdhLuJQAhdvR5Y.1nSvwCxJ1sK9paLLtqi5S",
                            UserName = "RobertWilliam12"
                        },
                        new
                        {
                            Id = new Guid("2a814a97-cbc6-4be6-9a6d-887eeba43d39"),
                            CoverUrl = "https://via.placeholder.com/150",
                            Email = "JamesMichael13@gmail.com",
                            FirstName = "James",
                            LastName = "Michael",
                            Password = "$2a$11$Hx.1.HZkvkfw7T52BbdhLuJQAhdvR5Y.1nSvwCxJ1sK9paLLtqi5S",
                            UserName = "JamesMichael13"
                        },
                        new
                        {
                            Id = new Guid("50ff2791-a009-4252-b302-2006bb2712f2"),
                            CoverUrl = "https://via.placeholder.com/150",
                            Email = "JamesThomas14@gmail.com",
                            FirstName = "James",
                            LastName = "Thomas",
                            Password = "$2a$11$Hx.1.HZkvkfw7T52BbdhLuJQAhdvR5Y.1nSvwCxJ1sK9paLLtqi5S",
                            UserName = "JamesThomas14"
                        },
                        new
                        {
                            Id = new Guid("bb5ab594-aecd-4365-ba51-dbeffc40a7c0"),
                            CoverUrl = "https://via.placeholder.com/150",
                            Email = "JohnMichael15@gmail.com",
                            FirstName = "John",
                            LastName = "Michael",
                            Password = "$2a$11$Hx.1.HZkvkfw7T52BbdhLuJQAhdvR5Y.1nSvwCxJ1sK9paLLtqi5S",
                            UserName = "JohnMichael15"
                        },
                        new
                        {
                            Id = new Guid("2f627f6e-f7a2-407c-8c95-890c08f8c285"),
                            CoverUrl = "https://via.placeholder.com/150",
                            Email = "JosephWilliam16@gmail.com",
                            FirstName = "Joseph",
                            LastName = "William",
                            Password = "$2a$11$Hx.1.HZkvkfw7T52BbdhLuJQAhdvR5Y.1nSvwCxJ1sK9paLLtqi5S",
                            UserName = "JosephWilliam16"
                        },
                        new
                        {
                            Id = new Guid("1338c622-25cc-46c0-bc09-018127721692"),
                            CoverUrl = "https://via.placeholder.com/150",
                            Email = "MichaelMichael17@gmail.com",
                            FirstName = "Michael",
                            LastName = "Michael",
                            Password = "$2a$11$Hx.1.HZkvkfw7T52BbdhLuJQAhdvR5Y.1nSvwCxJ1sK9paLLtqi5S",
                            UserName = "MichaelMichael17"
                        },
                        new
                        {
                            Id = new Guid("fb345d13-7f7e-4a77-b2cf-ae408bba3490"),
                            CoverUrl = "https://via.placeholder.com/150",
                            Email = "JosephJohn18@gmail.com",
                            FirstName = "Joseph",
                            LastName = "John",
                            Password = "$2a$11$Hx.1.HZkvkfw7T52BbdhLuJQAhdvR5Y.1nSvwCxJ1sK9paLLtqi5S",
                            UserName = "JosephJohn18"
                        },
                        new
                        {
                            Id = new Guid("62d890ce-3afc-47fd-86ad-e4808e3b51d3"),
                            CoverUrl = "https://via.placeholder.com/150",
                            Email = "JohnCharles19@gmail.com",
                            FirstName = "John",
                            LastName = "Charles",
                            Password = "$2a$11$Hx.1.HZkvkfw7T52BbdhLuJQAhdvR5Y.1nSvwCxJ1sK9paLLtqi5S",
                            UserName = "JohnCharles19"
                        });
                });

            modelBuilder.Entity("BarelyGambling.Core.Entity.Bidding", b =>
                {
                    b.HasOne("BarelyGambling.Core.Entity.Team", null)
                        .WithMany("Biddings")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarelyGambling.Core.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BarelyGambling.Core.Entity.Team", b =>
                {
                    b.HasOne("BarelyGambling.Core.Entity.Tournament", "Tournament")
                        .WithMany("Teams")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BarelyGambling.Core.Entity.TeamMember", b =>
                {
                    b.HasOne("BarelyGambling.Core.Entity.Team", null)
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarelyGambling.Core.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BarelyGambling.Core.Entity.Tournament", b =>
                {
                    b.HasOne("BarelyGambling.Core.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
